### PR TITLE
[PR 16039] ios Darwin_embedded build change

### PR DESCRIPTION
**Pull request by fuzzard**
https://github.com/xbmc/xbmc/pull/16039

Merge if/when the above is merged into kodi/master

### CODE REVIEW

**Review by Rechi — CHANGES_REQUESTED** [review]
This will break building the add-on for Leia as `CORE_SYSTEM_NAME` is still ios for Leia.

**Comment by fuzzard** [comment]
Can this be squashed at merge? Ive been doing the addons via the github webpage rather than a local repo, and i cant see how (if its even possible via web gui) to merge/rebase into single commit.

If it can, sweet, if not, let me know and ill do a proper local repo rebase

**Comment by phunkyfish** [comment]
Will need a proper local repo rebase. The github webpage cannot do this.

**Comment by phunkyfish** [comment]
This failed on loading the ming tarball, could someone kick off another build?

**Comment by hudokkow** [comment]
jenkins is happy!

**Pull request merged**
