### PR TITLE
FIX: include cpack

### PR DESCRIPTION
**Pull request by koying**

### CODE REVIEW

**Comment by garbear** [comment]
@fetzerch should this be pulled into `kodi-game-scripting`?

**Comment by fetzerch** [comment]
@garbear Sure, I'll can roll it out for all game addons.

**Comment by fetzerch** [comment]
Rolled out to all addons via https://github.com/fetzerch/kodi-game-scripting/commit/298bd431d416f33d42484320f5927847b62511fd.

**Pull request closed without merging**
