### PR TITLE
Fix linux depends build

### PR DESCRIPTION
**Pull request by AlwinEsch**
This is a fix about the build on my Linux.

### CODE REVIEW

**Comment by garbear** [comment]
@fetzerch if these changes look good we should update your game add-on script

**Comment by fetzerch** [comment]
CMake changes look good. @AlwinEsch: can you upload a build log and let me know what 'linux' that is? platform=unix is not necessary on ubuntu.

I'll can push this to all libretro cores through kodi-game-scripting at the end of the week.

**Comment by AlwinEsch** [comment]
Without the `platform=unix` try it to build a windows Dll and come out "2048_libretro.dll" or a error ;)

Here the error on direct build: http://pastebin.com/9ysGULKV
Here without the `platform=unix` with cmake: http://pastebin.com/ENcfQXWg
Here the working: http://pastebin.com/hAgcddcn

**Comment by fetzerch** [comment]
What is the output of uname -a on your machine? Just wondering why https://github.com/libretro/libretro-2048/blob/master/Makefile.libretro#L3 doesn't work. I'm not against explicitly mentioning platform=unix. I'm just curious.

**Comment by AlwinEsch** [comment]
Here the uname: Linux alwin-OMEN-by-HP-Laptop 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

EDIT: Is on Linux Mint

**Comment by fetzerch** [comment]
Haha! It finds alWIN :)

**Comment by fetzerch** [comment]
Unfortunately there are a few issues with this, I'll have a closer lock, but it'll take a couple of days.
platform=unix doesn't work for all cores - bnes (and maybe others) fail if that is set. The install change doesn't work for me when building locally (the same way that jenkins would build it).

**Comment by fetzerch** [comment]
@AlwinEsch: The platform=unix is fixed now in all cores. For the other issue about installing the cmake config file: Can you please provide detail steps how to reproduce this issue? If I recall correctly @lrusak also had a problem related to this a while ago. I'll try to find some time to look into it, but need an easy way to reproduce.

**Comment by garbear** [comment]
@AlwinEsch Does 2048 build successfully for you now?

**Comment by garbear** [comment]
Can this be closed?

**Comment by garbear** [comment]
@AlwinEsch I'm assuming this can be closed?

**Pull request closed without merging**
